version: '3.9'
services:
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    container_name: "erp_db_subscriptions"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=erp_db